version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/home/serveradmin/jdownloader-2:/config:rw"
      - "/mnt/media/downloads:/output:rw"