version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    environment:
      AUTOMATED_CONVERSION_PRESET: "Custom/HQ 4K HDR x265"
      AUTOMATED_CONVERSION_FORMAT: "mkv"
    ports:
      - "5800:5800"
    volumes:
      - "/home/serveradmin/Handbrake/config:/config:rw"
      - "/mnt/media:/storage:ro"
      - "/mnt/media/downloads/watch:/watch:rw"
      - "/mnt/media/converts:/output:rw"

